# Generated by Django 3.2.9 on 2021-11-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('user_browser', models.CharField(max_length=10000)),
                ('user_ip', models.GenericIPAddressField(unpack_ipv4=True)),
            ],
        ),
    ]
